CREATE DATABASE IF NOT EXISTS database_report
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE database_report;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `n_ata_qpa_xref_pn`;
CREATE TABLE `n_ata_qpa_xref_pn` (
`Aircraft0` varchar(20) DEFAULT '',
`Aircraft` varchar(20) DEFAULT '',
`Key` varchar(10) DEFAULT '',
`PartNo` text DEFAULT NULL,
`ATA` varchar(10) DEFAULT '',
`QPA` varchar(5) DEFAULT '',
`Mat_Type` varchar(10) DEFAULT '',
`PartName` varchar(255) DEFAULT '',
`FastM` varchar(10) DEFAULT '',
`Cabin` varchar(10) DEFAULT '',
`PartNo_text` text DEFAULT NULL,
`PartNo_space` text DEFAULT NULL,
`EMG` varchar(100) DEFAULT '',
`source` varchar(100) DEFAULT '',
`date_rev` varchar(100) DEFAULT '',
`Manufacturer` text DEFAULT NULL,
`document` varchar(200) DEFAULT NULL,
`functional_family` varchar(40) DEFAULT NULL,
`list_of_supplier` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `n_fleetdata`;
CREATE TABLE `n_fleetdata` (
`IDreg` varchar(20) DEFAULT '',
`IDType` varchar(20) DEFAULT '',
`ACReg` varchar(20) DEFAULT '',
`ACReg2` varchar(50) DEFAULT '',
`ACType0` varchar(50) DEFAULT '',
`ACType` varchar(50) DEFAULT '',
`ACType2` varchar(50) DEFAULT '',
`FleetID_` varchar(20) DEFAULT '',
`Operator` varchar(50) DEFAULT '',
`SerialModule` varchar(50) DEFAULT '',
`VariableNumber` varchar(20) DEFAULT '',
`SerialNumber` varchar(50) DEFAULT '',
`ManufYear` varchar(20) DEFAULT '',
`DEliveryDate` varchar(20) DEFAULT '',
`EngineType` varchar(50) DEFAULT '',
`Lessor` varchar(50) DEFAULT '',
`Active` varchar(20) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `n_ik17_raw`;
CREATE TABLE `n_ik17_raw` (
`MeasDocument` varchar(20) DEFAULT NULL,
`Equipment_ik` varchar(20) DEFAULT NULL,
`Description_ik` varchar(100) DEFAULT NULL,
`Measuring point` varchar(20) DEFAULT NULL,
`Origin_indic` varchar(20) DEFAULT NULL,
`Date` date DEFAULT NULL,
`MeasTotCtrRdg` varchar(20) DEFAULT NULL,
`Difference` varchar(20) DEFAULT NULL,
`Counter reading` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `n_sq00`;

CREATE TABLE `n_sq00` (
  `Part_Number` TEXT DEFAULT NULL,
  `Serial_number` TEXT DEFAULT NULL,
  `Equipment` VARCHAR(40) DEFAULT NULL,
  `Material_Description` VARCHAR(100) DEFAULT NULL,
  `Notification` VARCHAR(20) DEFAULT NULL,
  `Typ` VARCHAR(10) DEFAULT NULL,
  `Description` VARCHAR(50) DEFAULT NULL,
  `Dam.` VARCHAR(40) DEFAULT NULL,
  `Cs.` VARCHAR(40) DEFAULT NULL,
  `Mn_wk_ctr` VARCHAR(40) DEFAULT NULL,
  `Plnt WorkCenter` VARCHAR(40) DEFAULT NULL,
  `Profit Ctr` VARCHAR(40) DEFAULT NULL,
  `Functional_location_affected` VARCHAR(80) DEFAULT NULL,
  `CgrCode` VARCHAR(40) DEFAULT NULL,
  `Code` VARCHAR(40) DEFAULT NULL,
  `Short_Text` VARCHAR(40) DEFAULT NULL,
  `User_Status` VARCHAR(40) DEFAULT NULL,
  `Ref / Orig Order` VARCHAR(40) DEFAULT NULL,
  `Type` VARCHAR(40) DEFAULT NULL,
  `Notification_Orig` VARCHAR(40) DEFAULT NULL,
  `Typ_Notif_Orig` VARCHAR(40) DEFAULT NULL,
  `Description_Notif_Orig` VARCHAR(100) DEFAULT NULL,
  `Doc_Type` VARCHAR(40) DEFAULT NULL,
  `Document` VARCHAR(40) DEFAULT NULL,
  `DPt` VARCHAR(40) DEFAULT NULL,
  `Vr` VARCHAR(40) DEFAULT NULL,
  `Document_Description` VARCHAR(100) DEFAULT NULL,
  `Order2` VARCHAR(40) DEFAULT NULL,
  `Order2_Type` VARCHAR(40) DEFAULT NULL,
  `Notification2` VARCHAR(40) DEFAULT NULL,
  `Notif2_Type` VARCHAR(40) DEFAULT NULL,
  `Description2` VARCHAR(100) DEFAULT NULL,
  `Batch` VARCHAR(40) DEFAULT NULL,
  `Req_start` DATE DEFAULT NULL,
  `Notif_Date` DATE DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `n_tabelhasil_2`;

CREATE TABLE `n_tabelhasil_2` (
  `ID` VARCHAR(10) DEFAULT NULL,
  `ATA` VARCHAR(5) DEFAULT NULL,
  `AIN` VARCHAR(20) DEFAULT NULL,
  `PartNo` VARCHAR(20) DEFAULT NULL,
  `SerialNo` VARCHAR(20) DEFAULT NULL,
  `PartName` VARCHAR(50) DEFAULT NULL,
  `REG` VARCHAR(20) DEFAULT NULL,
  `Aircraft` VARCHAR(20) DEFAULT NULL,
  `Month_` VARCHAR(20) DEFAULT '',
  `Qty` VARCHAR(20) DEFAULT NULL,
  `Addtl_Info_Loc` VARCHAR(20) DEFAULT '',
  `Work_Center` VARCHAR(20) DEFAULT '',
  `RemCodeXXX` VARCHAR(20) DEFAULT NULL,
  `Reason` VARCHAR(100) DEFAULT '',
  `RealReason` LONGTEXT DEFAULT NULL,
  `Originating_Order` VARCHAR(20) DEFAULT '',
  `Originating_Order_Desc` VARCHAR(255) DEFAULT '',
  `Maintenance_Item_Type` VARCHAR(20) DEFAULT '',
  `Maintenance_Item` VARCHAR(20) DEFAULT '',
  `First_Notification_Trigger` VARCHAR(20) DEFAULT '',
  `Related_AML_Prob` VARCHAR(255) DEFAULT '',
  `Related_AML_Rect` VARCHAR(255) DEFAULT '',
  `NFF` VARCHAR(20) DEFAULT '',
  `DateRem` DATE DEFAULT NULL,
  `Year_` VARCHAR(20) DEFAULT '',
  `Serviceable` VARCHAR(20) DEFAULT NULL,
  `Shop_Notification` VARCHAR(20) DEFAULT NULL,
  `Shop_Visit` VARCHAR(255) DEFAULT '',
  `Shop_Finding` VARCHAR(255) DEFAULT '',
  `XXX` VARCHAR(20) DEFAULT NULL,
  `Originating_Orderx` VARCHAR(20) DEFAULT '',
  `Orig_Order_Type` VARCHAR(20) DEFAULT NULL,
  `Orig_Order_Notif` VARCHAR(20) DEFAULT NULL,
  `Orig_Order_Notif_Type` VARCHAR(20) DEFAULT NULL,
  `Orig_Order_Notif_Desc` VARCHAR(255) DEFAULT NULL,
  `Order2` VARCHAR(20) DEFAULT NULL,
  `Order2_Type` VARCHAR(20) DEFAULT NULL,
  `Notif2_Type` VARCHAR(20) DEFAULT NULL,
  `Mat_Type` VARCHAR(20) DEFAULT NULL,
  `FastM` VARCHAR(20) DEFAULT NULL,
  `Cabin` VARCHAR(20) DEFAULT NULL,
  `FECOD` VARCHAR(10) DEFAULT NULL,
  `URCOD` VARCHAR(10) DEFAULT NULL
) ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `n_tabelhasil_3`;

CREATE TABLE `n_tabelhasil_3` (
  `ID` VARCHAR(10) DEFAULT NULL,
  `ATA` VARCHAR(5) DEFAULT NULL,
  `AIN` VARCHAR(20) DEFAULT NULL,
  `PartNo` TEXT DEFAULT NULL,
  `SerialNo` TEXT DEFAULT NULL,
  `PartName` VARCHAR(50) DEFAULT NULL,
  `REG` VARCHAR(20) DEFAULT NULL,
  `Aircraft` VARCHAR(20) DEFAULT NULL,
  `Month` VARCHAR(20) DEFAULT NULL,
  `Qty` VARCHAR(20) DEFAULT NULL,
  `Addtl Info - Loc` VARCHAR(20) DEFAULT NULL,
  `Work Center` VARCHAR(20) DEFAULT NULL,
  `RemCodeXXX` VARCHAR(20) DEFAULT NULL,
  `Reason` VARCHAR(100) DEFAULT '',
  `RealReason` VARCHAR(255) DEFAULT NULL,
  `Originating Order` VARCHAR(20) DEFAULT NULL,
  `Originating Order Desc` VARCHAR(255) DEFAULT NULL,
  `Maintenance Item Type` VARCHAR(20) DEFAULT NULL,
  `Maintenance Item` VARCHAR(20) DEFAULT NULL,
  `First Notification Trigger` VARCHAR(20) DEFAULT NULL,
  `Related AML - Prob` VARCHAR(255) DEFAULT NULL,
  `Related AML - Rect` VARCHAR(255) DEFAULT NULL,
  `NFF` VARCHAR(20) DEFAULT NULL,
  `DateRem` DATE DEFAULT NULL,
  `Year` VARCHAR(20) DEFAULT NULL,
  `TSN` VARCHAR(20) DEFAULT NULL,
  `TSI` VARCHAR(20) DEFAULT NULL,
  `TSO` VARCHAR(20) DEFAULT NULL,
  `TSC` VARCHAR(20) DEFAULT NULL,
  `CSN` VARCHAR(20) DEFAULT NULL,
  `CSI` VARCHAR(20) DEFAULT NULL,
  `CSO` VARCHAR(20) DEFAULT NULL,
  `CSC` VARCHAR(20) DEFAULT NULL,
  `Serviceable` VARCHAR(20) DEFAULT NULL,
  `Shop_Notification` VARCHAR(20) DEFAULT NULL,
  `Shop_Visit` VARCHAR(255) DEFAULT '',
  `Shop_Finding` VARCHAR(255) DEFAULT '',
  `XXX` VARCHAR(20) DEFAULT NULL,
  `Originating_Order` VARCHAR(20) DEFAULT NULL,
  `Orig_Order_Type` VARCHAR(20) DEFAULT NULL,
  `Orig_Order_Notif` VARCHAR(20) DEFAULT NULL,
  `Orig_Order_Notif_Type` VARCHAR(20) DEFAULT NULL,
  `Orig_Order_Notif_Desc` VARCHAR(255) DEFAULT NULL,
  `Order2` VARCHAR(20) DEFAULT NULL,
  `Order2_Type` VARCHAR(20) DEFAULT NULL,
  `Notif2_Type` VARCHAR(20) DEFAULT NULL,
  `Mat_Type` VARCHAR(20) DEFAULT NULL,
  `FastM` VARCHAR(20) DEFAULT NULL,
  `Cabin` VARCHAR(20) DEFAULT NULL,
  `FECOD` VARCHAR(10) DEFAULT NULL,
  `URCOD` VARCHAR(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `n_tbl_notif_d8`;

CREATE TABLE `n_tbl_notif_d8` (
  `QMNUM` VARCHAR(20) DEFAULT NULL,
  `QMART` VARCHAR(20) DEFAULT NULL,
  `EQUNR` VARCHAR(20) DEFAULT NULL,
  `BTPLN` VARCHAR(100) DEFAULT NULL,
  `PLTXT` VARCHAR(255) DEFAULT NULL,
  `MATNR` VARCHAR(50) DEFAULT NULL,
  `MAKTX` VARCHAR(50) DEFAULT NULL,
  `SERIALNR` VARCHAR(50) DEFAULT NULL,
  `QMDAT` DATE DEFAULT NULL,
  `ERDAT` DATE DEFAULT NULL,
  `AEDAT` DATE DEFAULT NULL,
  `QMTXT` VARCHAR(50) DEFAULT NULL,
  `FECOD` VARCHAR(50) DEFAULT NULL,
  `URCOD` VARCHAR(50) DEFAULT NULL,
  `QMCOD` VARCHAR(50) DEFAULT NULL,
  `KURZTEXT` VARCHAR(50) DEFAULT NULL,
  `SMR_DEFORD` VARCHAR(50) DEFAULT NULL,
  `SMR_TECHLOG` VARCHAR(50) DEFAULT NULL,
  `LTEXT` VARCHAR(100) DEFAULT NULL,
  `UPDATE_DATE` DATE DEFAULT NULL,
  `SMR_CHARG` VARCHAR(50) DEFAULT NULL,
  `STTXT` VARCHAR(50) DEFAULT NULL,
  `USTXT` VARCHAR(50) DEFAULT NULL,
  `SMR_DEFORD_detect` VARCHAR(50) DEFAULT NULL,
  `SMR_DEFORD_techlog` VARCHAR(50) DEFAULT NULL
) ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `n_zabiw29_amlcml`;

CREATE TABLE `n_zabiw29_amlcml` (
  `Notification_amlcml` VARCHAR(20) DEFAULT NULL,
  `Notification Date` DATE DEFAULT NULL,
  `Functional Location` VARCHAR(20) DEFAULT NULL,
  `Fault Code` VARCHAR(20) DEFAULT NULL,
  `Defect Code` VARCHAR(20) DEFAULT NULL,
  `Departure Station` VARCHAR(20) DEFAULT NULL,
  `Arrival Station` VARCHAR(20) DEFAULT NULL,
  `Service` VARCHAR(100) DEFAULT NULL,
  `Defect Symptoms` VARCHAR(20) DEFAULT NULL,
  `Action Taken` VARCHAR(100) DEFAULT NULL,
  `Sector Reference` VARCHAR(20) DEFAULT NULL,
  `Notification_Description` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `n_zabiw29_w1`;

CREATE TABLE `n_zabiw29_w1` (
  `Notification_W1` VARCHAR(20) DEFAULT NULL,
  `Notification_Date_W1` DATE DEFAULT NULL,
  `Functional Location_W1` VARCHAR(100) DEFAULT NULL,
  `Fault Code_W1` VARCHAR(20) DEFAULT NULL,
  `Defect Code_W1` VARCHAR(20) DEFAULT NULL,
  `Departure Station_W1` VARCHAR(20) DEFAULT NULL,
  `Arrival Station_W1` VARCHAR(20) DEFAULT NULL,
  `Service_W1` VARCHAR(20) DEFAULT NULL,
  `Defect Symptoms_W1` VARCHAR(50) DEFAULT NULL,
  `Action Taken_W1` VARCHAR(100) DEFAULT NULL,
  `Sector Reference_W1` VARCHAR(50) DEFAULT NULL,
  `Notification_Description_W1` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;

DROP TABLE IF EXISTS `n_zascmsord`;

CREATE TABLE `n_zascmsord` (
  `AUART` VARCHAR(40) DEFAULT NULL,
  `AUFNR` VARCHAR(40) DEFAULT NULL,
  `KTEXT` VARCHAR(255) DEFAULT NULL,
  `PLGRP` VARCHAR(40) DEFAULT NULL,
  `VAPLZ` VARCHAR(40) DEFAULT NULL,
  `VAWRK` VARCHAR(40) DEFAULT NULL,
  `ILART` VARCHAR(40) DEFAULT NULL,
  `REVNR` VARCHAR(40) DEFAULT NULL,
  `REVTX` VARCHAR(255) DEFAULT NULL,
  `TPLNR` VARCHAR(40) DEFAULT NULL,
  `EQART` VARCHAR(40) DEFAULT NULL,
  `PLNNR` VARCHAR(40) DEFAULT NULL,
  `ADPSP` VARCHAR(40) DEFAULT NULL,
  `DOKAR` VARCHAR(40) DEFAULT NULL,
  `DOKNR` VARCHAR(40) DEFAULT NULL,
  `DOKTL` VARCHAR(40) DEFAULT NULL,
  `DOKVR` VARCHAR(40) DEFAULT NULL,
  `ERDAT_CMSORD` VARCHAR(40) DEFAULT NULL,
  `DEFORD` VARCHAR(40) DEFAULT NULL,
  `NACHN` VARCHAR(40) DEFAULT NULL,
  `MATNR_CMSORD` VARCHAR(40) DEFAULT NULL,
  `SERNR` VARCHAR(40) DEFAULT NULL,
  `FLAG` VARCHAR(40) DEFAULT NULL,
  `SEQUENCE` VARCHAR(40) DEFAULT NULL,
  `BEGRU` VARCHAR(40) DEFAULT NULL,
  `PLTXT_CMSORD` VARCHAR(40) DEFAULT NULL,
  `ENTERED_BY` VARCHAR(40) DEFAULT NULL,
  `SMRTPLNR` VARCHAR(40) DEFAULT NULL,
  `MATERIAL` VARCHAR(40) DEFAULT NULL,
  `MAKTX_CMSORD` VARCHAR(40) DEFAULT NULL,
  `SERIALNO` VARCHAR(40) DEFAULT NULL,
  `EQART2` VARCHAR(40) DEFAULT NULL,
  `QTY` VARCHAR(40) DEFAULT NULL,
  `START_DATE` DATE DEFAULT NULL,
  `FINISH_DATE` DATE DEFAULT NULL,
  `SMRD8NOTIF` VARCHAR(40) DEFAULT NULL,
  `FUNCLOC` VARCHAR(40) DEFAULT NULL,
  `TDLINE_HDR` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;